server:
  port: 9080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      start-saga: start-saga
      finish-success: finish-success
      finish-fail: finish-fail
      orchestrator: orchestrator
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest

logging:
  level:
    org:
      apache:
        kafka: OFF

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
