server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: relational-database-service
          uri: http://relational-database-service
          predicates:
            - Path=/relational-database-service/**
        - id: document-database-service
          uri: http://document-database-service
          predicates:
            - Path=/document-database-service/**
        - id: graph-database-service
          uri: http://graph-database-service
          predicates:
            - Path=/graph-database-service/**
        - id: columnar-database-service
          uri: http://document-database-service
          predicates:
            - Path=/document-database-service/**
        - id: columnar-database-service
          uri: http://columnar-database-service
          predicates:
            - Path=/columnar-database-service/**
        - id: elasticsearch-database-service
          uri: http://elasticsearch-database-service
          predicates:
            - Path=/elasticsearch-database-service/**
        - id: timeseries-database-service
          uri: http://timeseries-database-service
          predicates:
            - Path=/timeseries-database-service/**
        - id: vector-database-service
          uri: http://vector-database-service
          predicates:
            - Path=/vector-database-service

