server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: relational-database-service
          uri: http://relational-database-service
          predicates:
            - Path=/relational-database-service/**
        - id: graph-database-service
          uri: http://graph-database-service
          predicates:
            - Path=/graph-database-service/**
        - id: elasticsearch-database-service
          uri: http://elasticsearch-database-service
          predicates:
            - Path=/elasticsearch-database-service/**
